### ISSUE TITLE
Add field Timestamp

### ISSUE THREAD

**Issue by richecr** [richecr/duck-orm#15]
### Add field:
- Timestamp

Support for **postgresql** and **sqlite**.

In Postgresql: https://www.postgresql.org/docs/9.1/datatype-datetime.html
On sqlite: https://www.sqlite.org/datatype3.html

When at the python level the user should be able to access all the methods of the `datetime.datetime` class in Python.

**Comment by lucascz37** [comment]
Can you assign this one to me?

**Comment by richecr** [comment]
It's all yours, any questions just speak here.
