### ISSUE TITLE
Add the `on_delete` parameters to the `ForeignKey` field

### ISSUE THREAD

**Issue by richecr** [richecr/duck-orm#17]
The options available for these parameters:
- SET NULL
- SET DEFAULT
- RESTRICT
- NO ACTION
- CASCADE

The default value is: NO ACTION

Reference Postgres: https://www.postgresqltutorial.com/postgresql-foreign-key/
Reference SQLite: https://www.sqlitetutorial.net/sqlite-foreign-key/

**Comment by yuri-s-s** [comment]
Can you assign this one to me?
